# Generated by Django 4.2.7 on 2025-11-29 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WakeUpCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this wake-up call', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number to call/text', max_length=128, region=None)),
                ('contact_method', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'Text Message')], default='call', max_length=10)),
                ('scheduled_time', models.TimeField(help_text='Time to make the wake-up call')),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays Only'), ('weekends', 'Weekends Only'), ('custom', 'Custom')], default='once', max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('include_weather', models.BooleanField(default=True)),
                ('weather_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('custom_message', models.TextField(blank=True, help_text='Custom message to include', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('is_demo', models.BooleanField(default=False, help_text="Demo calls won't actually be made")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('next_execution', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wakeup_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_execution', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='WakeUpCallExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('twilio_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('twilio_status', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_response', models.CharField(blank=True, max_length=20, null=True)),
                ('interaction_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wakeup_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='wakeup_calls.wakeupcall')),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
