# Generated by Django 4.2.7 on 2025-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakeup_calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wakeupcallexecution',
            name='is_snooze',
            field=models.BooleanField(default=False, help_text='True if this is a snooze call'),
        ),
    ]
